name: Build Kernel Dumper
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scene-collective/ps4-payload-sdk:latest # Provides the PS4 toolchain natively
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build payload
        run: |
          make

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Automagic Build"
          draft: false
          prerelease: false
          files: "*.bin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
