name: Build Kernel Dumper
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install PS4 SDK Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc make git
          git clone https://github.com ~/ps4-payload-sdk
          cd ~/ps4-payload-sdk
          chmod +x install.sh
          sudo ./install.sh

      - name: Build payload
        run: |
          export PS4SDK=/lib/ps4-payload-sdk
          make

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Automagic Build"
          draft: false
          prerelease: false
          files: "*.bin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
